const styles = {
  parallaxContainer: {
    position: "relative",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    mt: "50px",
    mb: "50px",
    paddingX: {
      xs: "20px",
      md: "220px",
    },
  },
  imageContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  userCardCSS: {
    display: { md: "block", xs: "none" },
    background: "rgba(35, 30, 68, 1)",
    border: "0.5px solid rgba(58, 56, 79, 1)",
    boxShadow: "0px 0px 40.7px 0px rgba(115, 112, 142, 0.23)",
    padding: "10px",
    minWidth: "180px",
    borderRadius: "10px",
    flexGrow: 1,
    "& h1": {
      fontSize: {
        xs: "14px",
        md: "19px",
      },
      fontWeight: "600",
      color: "rgba(142, 84, 233, 1)",
    },
    "& body1": {
      fontSize: {
        xs: "12px",
        md: "15px",
      },
      textWrap: "nowrap",
      fontWeight: "400",
      color: "#fff",
    },
  },
  parallaxImage: {
    position: "absolute",
  },
  topLeft: {
    width: { xs: "120", md: "154" },
    height: { xs: "120px", md: "74px" },
    top: {
      xs: "10%",
      md: "10%",
    },
    left: {
      xs: "10%",
      md: "20%",
    },
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  topRight: {
    top: {
      xs: "10%",
      md: "10%",
    },
    right: {
      xs: "5%",
      md: "10%",
    },
    width: { xs: "120", md: "154" },
    height: { xs: "120px", md: "74px" },
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  bottomLeft: {
    width: { xs: "80px", md: "172px" },
    height: { xs: "80px", md: "172px" },
   
    display: "flex",
    alignItems: "center",
    gap: "20px",
    bottom: {
      xs: "10%",
      md: "10%",
    },
    left: {
      xs: "13%",
      md: "10%",
    },
  },
  bottomRight: {
    width: { xs: "80px", md: "110px" },
    height: { xs: "80px", md: "110px" },
    bottom: {
      xs: "15%",
      md: "10%",
    },
    right: {
      xs: "10%",
      md: "20%",
    },
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  centerContent: {
    zIndex: 1,
    textAlign: "center",
    color: "#fff",
    "& h4": {
      fontSize: {
        xs: "18px",
        md: "57px",
      },
      color: "#fff",
      textAlign: "center",
      marginTop: "40px",
      fontWeight: "700",
    },
    "& .MuiTypography-body1": {
      fontSize: {
        xs: "18px",
        md: "57px",
      },
      background: "linear-gradient(92.89deg, #8E54E9 3.96%, #4776E6 32.74%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      display: "inline",
    },
  },
  user4Card: {
    display: { md: "block", xs: "none" },
    background: "rgba(35, 30, 68, 1)",
    border: "0.5px solid rgba(58, 56, 79, 1)",
    boxShadow: "0px 0px 40.7px 0px rgba(115, 112, 142, 0.23)",
    padding: "10px",
    borderRadius: "10px",
    minWidth: "180px",
    flexGrow: 1,
    "& h1": {
      fontSize: {
        xs: "14px",
        md: "19px",
      },
      fontWeight: "600",
      color: "rgba(142, 84, 233, 1)",
    },
    "& body1": {
      fontSize: {
        xs: "12px",
        md: "15px",
      },
      textWrap: "nowrap",
      fontWeight: "400",
      color: "#fff",
    },
  },
  joinButton: {
    marginTop: "20px",
    padding: "20px 30px",
    color: "#fff",
    background: "linear-gradient(93.53deg, #3E57A7 11.57%, #86CDB6 99.84%)",
    "&:hover": {
      backgroundColor: "rgba(110, 180, 158, 1)",
    },
  },
  ringContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
  },
  ringCSS: {
    position: "absolute",
    borderRadius: "50%",
    border: "1px solid #fff",
    animation: "glow 5s infinite ease-in-out",
    opacity: 0,
    transition: "opacity 0.6s ease-in-out",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
  },
  mainCSS: {
    position: "absolute",
    width: "400px",
    height: "400px",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    borderRadius: "50%",
    overflow: "visible",
  },
  circleCSS: {
    position: "absolute",
    animation: "glow 4s infinite alternate",
    top: "50%",
    left: "50%",
    width: "30px",
    height: "30px",
    background: "cyan",
    borderRadius: "50%",
    margin: "0",
    transform: `translate(-50%, -50%)`,
    animation: `orbit 6s linear infinite`,
    transformOrigin: "0 -165px",
  },
};

export default styles;
