const styles = {
  ContainerCSS: {
    position: "relative",
    width: "100%",
    height: "70vh",
    overflow: "hidden",
    display: "flex",
    alignItems: "flex-end",
    padding: "20px",
    boxSizing: "border-box",
    zIndex: 1,
  },
  contentContainer: {
    position: "relative",
    color: "#fff",
    zIndex: 2,
    left: "100px",
    maxWidth: "500px",
    marginBottom: "50px",
    "& h2": {
      fontWeight: 500,
      display: "flex",
      alignItems: "center",
      fontSize: "70px",
      flexDirection: "row",
      textAlign: "center",
      gap: "11px",
      justifyContent: "center",
      alignItems: "center",
    },
  },
  buttonContainer: {
    marginTop: "20px",
    display: "flex",
    alignItems: "center",
    backgroundColor: "transparent",
    color: "#fff",
    padding: "10px 20px",
    borderRadius: "25px",
    textTransform: "none",
    border: "2px solid rgba(255, 153, 0, 1)",
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  imageContainer: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "20px",
  },
  modelContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "70vh",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    backdropFilter: "blur(10px)",
    transition: "all 0.4s ease",
    padding: { xs: "20px", md: "40px" },
  },
  closeIconCSS: {
    position: "absolute",
    top: "10px",
    right: "10px",
    color: "white",
    zIndex: 10,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.4)",
    },
  },
  videoModelCSS: {
    position: "relative",
    width: { xs: "100%", md: "80%" },
    maxHeight: { xs: "70vh", md: "80vh" },
    backgroundColor: "black",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0px 6px 30px rgba(0, 0, 0, 0.6)",
    transition: "all 0.4s ease",
  },
};

export default styles;
