const styles = {
  container: {
    padding: { xs: "20px", sm: "30px", md: "50px" },
    maxWidth: "1400px",
    margin: "0 auto",
    textAlign: "center",
    color: "#fff",
  },
  subContainer: {
    textAlign: "center",
    mb: { xs: 6, sm: 8, md: 12 },
    "& h6": {
      fontSize: { xs: "16px", sm: "21px", md: "23px" },
      fontWeight: "600",
      lineHeight: { xs: "22px", sm: "25px", md: "27px" },
      color: "rgba(221, 204, 248, 1)",
    },
    "& body1": {
      fontSize: { xs: "22px", sm: "44px", md: "57px" },
      fontWeight: "600",
      lineHeight: { xs: "42px", sm: "54px", md: "100px" },
      color: "rgba(246, 246, 246, 1)",
      maxWidth: "875px",
      margin: "10px auto",
    },
    "& body2": {
      fontSize: { xs: "14px", sm: "16px", md: "18px" },
      fontWeight: "400",
      lineHeight: { xs: "20px", sm: "24px", md: "27px" },
      color: "gray",
      maxWidth: "700px",
      margin: "10px auto",
    },
  },
  cardContainer: {
    height: { xs: "705px", sm: "600px", md: "705px" },
    maxHeight: "705px",
    width: { xs: "100%", sm: "380px", md: "405px" },
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "20px",
    position: "relative",
    borderRadius: "10px",
    textAlign: "left",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    boxShadow: "0 8px 16px rgba(255, 255, 255, 0.1)",
    "&:hover": {
      transform: "translateY(-15px)",
      boxShadow: "0 8px 16px rgba(255, 255, 255, 0.4)",
    },
  },
  cardImageContainer: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "rgba(35, 30, 68, 1)",
    borderRadius: "10px",
    padding: "10px",
    border: "1px solid rgba(35, 30, 68, 1)",
    "& img": {
      width: { xs: "30px", sm: "35px", md: "40px" },
      height: { xs: "30px", sm: "35px", md: "40px" },
    },
  },
  cardContainerCSS: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    justifyContent: "flex-end",
    color: "#fff",
    "& h5": {
      color: "#FFFFFF",
      mb: 1,
      fontSize: { xs: "22px", sm: "30px", md: "36px" },
      fontWeight: "500",
      lineHeight: { xs: "30px", sm: "36px", md: "42px" },
    },
    "& body1": {
      color: "#CCCCCC",
      fontSize: { xs: "16px", sm: "17px", md: "18px" },
      fontWeight: "300",
      lineHeight: { xs: "16px", sm: "25px", md: "27px" },
      mb: 2,
    },
    "& body2": {
      color: "#fff",
      fontWeight: "300",
      fontSize: { xs: "13px", sm: "14px", md: "15px" },
      textAlign: "left",
      whiteSpace: "pre-wrap",
      lineHeight: { xs: "20px", sm: "21px", md: "16px" },
    },
  },
  getStartedBtn: {
    backgroundColor: "rgba(115, 68, 190, 1)",
    color: "#FFFFFF",
    textTransform: "none",
    fontSize: { xs: "14px", sm: "18px", md: "19px" },
    fontWeight: "500",
    lineHeight: { xs: "20px", sm: "21px", md: "22px" },
    padding: { xs: "8px 16px", sm: "9px 18px", md: "10px 20px" },
    width: { xs: "220px", sm: "240px", md: "260px" },
    "&:hover": {
      backgroundColor: "rgba(115, 68, 190, 0.9)",
    },
  },
};

export default styles;
