const styles = {
  containerCSS: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "1400px",
    width: "100%",
    margin: "0 auto",
    padding: { xs: "20px", sm: "30px", md: "50px" },
    color: "#fff",
    mt: { xs: 4, md: 6 },
    mb: { xs: 4, md: 6 },
    position: "relative",
    paddingTop: { xs: "20px", md: "50px" },
    "& h2": {
      fontSize: { xs: "28px", md: "48px" },
      fontWeight: "700",
      marginBottom: "10px",
    },
    "& body1": {
      fontSize: { xs: "14px", md: "16px" },
      fontWeight: "400",
      color: "rgba(255, 255, 255, 0.7)",
    },
  },
  leaderContainerCard: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    flexWrap: "wrap",
    gap: "15px",
  },
  leaderCard: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    width: { xs: "100%", md: "665px" },
    height: { xs: "auto", md: "284px" },
    boxSizing: "border-box",
  },
  imageContainer: {
    width: { xs: "100%", md: "40%" },
    height: { xs: "400px", md: "100%" },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: "10px",
    backgroundColor: "rgba(240, 240, 240, 1)",
    padding: "20px",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "10px",
  },
  leaderContentCSS: {
    width: { xs: "100%", md: "60%" },
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: { xs: "10px", md: "20px" },
    boxSizing: "border-box",
    "& h6": {
      fontSize: { xs: "18px", md: "20px" },
      fontWeight: "700",
    },
    "& body1": {
      fontSize: { xs: "14px", md: "16px" },
      fontWeight: "400",
      color: "rgba(0, 0, 0, 0.7)",
    },
    "& body2": {
      fontSize: { xs: "12px", md: "14px" },
      fontWeight: "400",
      color: "rgba(0, 0, 0, 0.7)",
      marginTop: { xs: "20px", md: "30px" },
    },
  },
  socialIcons: {
    display: "flex",
    gap: "10px",
    marginTop: { xs: "5px", md: "10px" },
  },
  teamConatiner: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", md: "repeat(3, 1fr)" },
    gap: "2rem",
  },
  teamCard: {
    cursor: "pointer",
    color: "#fff",
    transition: "0.3s",
    background: "rgba(30, 28, 48, 1)",
    "&:hover": { transform: "scale(1.05)", boxShadow: 3 },
    "& img": {
      borderRadius: "50%",
      objectFit: "cover",
      height: "150px",
      margin: "0 auto",
    },
  },
  modalConatiner: {
    background: "#0B081E",
    borderRadius: 2,
    color: "#fff",
    boxShadow: 24,
    p: 4,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: { xs: "80%", sm: "60%", md: "40%" },
    maxHeight: "80%",
    overflowY: "auto",
    textAlign: "center",
  },
  buttonCSS: {
    marginTop: "1rem",
    width: { xs: "150px", md: "350px" },
    background: "linear-gradient(93.53deg, #3E57A7 11.57%, #86CDB6 99.84%)",
    color: "#fff",
    marginLeft: "auto",
    marginRight: "auto",
    padding: "8px 20px",
    fontWeight: "bold",
    textTransform: "none",
    transition: "none",
    "&:hover": {
      backgroundColor: "rgba(110, 180, 158, 1)",
    },
  },
};

export default styles;
